name: ci_x86_64_linux_musl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install musl-tools
      run: sudo apt-get install --yes --no-install-recommends musl-tools

    - name: Install Rustup targets
      run : | 
        rustup target add x86_64-unknown-linux-musl

    - name: Check out source code
      uses: actions/checkout@v3

    - name: Test _IEEE_LIBM for x86_64-unknown-linux-musl
      run:  _IEEE_LIBM="" cargo  test --target x86_64-unknown-linux-musl

    - name: Test _IEEE_MODE for x86_64-unknown-linux-musl
      run:  _IEEE_MODE="" cargo  test --target x86_64-unknown-linux-musl
    
    - name: Test _XOPEN_MODE for x86_64-unknown-linux-musl
      run:  _XOPEN_MODE="" cargo  test --target x86_64-unknown-linux-musl
    
    - name: Test _POSIX_MODE for x86_64-unknown-linux-musl
      run:  _POSIX_MODE="" cargo  test --target x86_64-unknown-linux-musl
    
    - name: Test _SVID3_MODE for x86_64-unknown-linux-musl
      run:  _SVID3_MODE="" cargo  test --target x86_64-unknown-linux-musl

    - name: Build x86_64-linux-musl 
      run: cargo build --target x86_64-unknown-linux-musl 