name: ci_x86_64_pc_windows_gnu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install cross-rs
      run: |
        cargo install cross --git https://github.com/cross-rs/cross

    - name: Check out source code
      uses: actions/checkout@v3

    - name: Test _IEEE_LIBM for x86_64-pc-windows-gnu
      run:  _IEEE_LIBM="" cross test --target x86_64-pc-windows-gnu

    - name: Test _IEEE_MODE for x86_64-pc-windows-gnu
      run:  _IEEE_MODE="" cross test --target x86_64-pc-windows-gnu

    - name: Test _XOPEN_MODE for x86_64-pc-windows-gnu
      run:  _XOPEN_MODE="" cross test --target x86_64-pc-windows-gnu

    - name: Test _POSIX_MODE for x86_64-pc-windows-gnu
      run:  _POSIX_MODE="" cross test --target x86_64-pc-windows-gnu

    - name: Test _SVID3_MODE for x86_64-pc-windows-gnu
      run:  _SVID3_MODE="" cross test --target x86_64-pc-windows-gnu

    - name: Build x86_64-pc-windows-gnu
      run: cross build --target x86_64-pc-windows-gnu